"""LLM-generated narrative (monthly commentary + outlook) for the fund tear sheet.

The text is generated by Claude from a compact dict of performance facts and
cached in app.db keyed by (fund_id, as_of). The fund report endpoint is
``Cache-Control: no-store`` (regenerated on every fetch), so without this cache
an LLM call would fire on every request; with it the call fires once per as-of
date — or again only when the underlying numbers change (guarded by data_hash).
Degrades gracefully to no narrative if the SDK/key is unavailable or the call
fails — the report still renders, just without commentary.
"""
import re
import os
import sys
import json
import sqlite3
import hashlib
import asyncio
from datetime import datetime, timezone
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent.parent.parent / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from db_config import APP_DB_PATH  # noqa: E402

MODEL = "claude-opus-4-7"

_SYSTEM_PROMPT = """You are the investor-communications analyst for a systematic \
equity fund, writing the narrative for a monthly investor report read by \
sophisticated investors. Ground every statement in the numbers you are given — \
never invent figures, holdings, or market events not present in the data. Be \
concise, factual and measured. Do not give guarantees, price targets, or \
promises about future returns; frame the outlook in terms of strategy \
positioning and risk, not predictions.

Return STRICT JSON only (no markdown, no prose outside the JSON) with exactly \
two string keys:
  "commentary": 1-2 short paragraphs on the period's performance and what drove it.
  "outlook":    1 short paragraph of measured forward-looking positioning.
"""


def _conn() -> sqlite3.Connection:
    from schema import init_db
    conn = sqlite3.connect(str(APP_DB_PATH))
    conn.row_factory = sqlite3.Row
    init_db(conn)
    return conn


def _hash(facts: dict) -> str:
    return hashlib.sha256(
        json.dumps(facts, sort_keys=True, default=str).encode()
    ).hexdigest()


def _parse(raw: str) -> dict | None:
    if not raw:
        return None
    m = re.search(r"\{.*\}", raw, re.DOTALL)
    if not m:
        return None
    try:
        obj = json.loads(m.group(0))
    except Exception:
        return None
    commentary = (obj.get("commentary") or "").strip()
    outlook = (obj.get("outlook") or "").strip()
    if not commentary and not outlook:
        return None
    return {"commentary": commentary, "outlook": outlook}


async def _generate(facts: dict) -> dict | None:
    try:
        from claude_agent_sdk import query, ClaudeAgentOptions
    except Exception:
        return None
    opts = {
        "model": MODEL,
        "system_prompt": _SYSTEM_PROMPT,
        "allowed_tools": [],
        "max_turns": 1,
        "permission_mode": "default",
    }
    user_prompt = "Fund performance facts (JSON):\n" + json.dumps(facts, indent=2, default=str)
    pieces: list[str] = []
    result_text: str | None = None
    async for message in query(prompt=user_prompt, options=ClaudeAgentOptions(**opts)):
        if hasattr(message, "result") and message.result:
            result_text = message.result
        elif type(message).__name__ == "AssistantMessage":
            content = getattr(message, "content", [])
            for block in (content if isinstance(content, list) else [content]):
                if type(block).__name__ == "TextBlock":
                    pieces.append(block.text)
    return _parse(result_text if result_text is not None else "\n".join(pieces))


def get_commentary(fund_id: str, as_of: str, facts: dict) -> dict | None:
    """Cached {commentary, outlook} for (fund_id, as_of). Reuses the cached row
    if its facts hash matches; otherwise generates via the LLM, caches, returns.
    Returns None (no narrative) if generation is unavailable or fails."""
    h = _hash(facts)
    conn = _conn()
    try:
        row = conn.execute(
            "SELECT data_hash, commentary, outlook FROM fund_report_commentary "
            "WHERE fund_id = ? AND as_of = ?",
            (fund_id, as_of),
        ).fetchone()
        if row and row["data_hash"] == h:
            return {"commentary": row["commentary"], "outlook": row["outlook"]}
    finally:
        conn.close()

    try:
        out = asyncio.run(_generate(facts))
    except Exception:
        out = None
    if not out:
        return None

    conn = _conn()
    try:
        conn.execute(
            """INSERT INTO fund_report_commentary
                 (fund_id, as_of, data_hash, commentary, outlook, model, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?)
               ON CONFLICT(fund_id, as_of) DO UPDATE SET
                 data_hash = excluded.data_hash, commentary = excluded.commentary,
                 outlook = excluded.outlook, model = excluded.model,
                 created_at = excluded.created_at""",
            (fund_id, as_of, h, out["commentary"], out["outlook"], MODEL,
             datetime.now(timezone.utc).isoformat()),
        )
        conn.commit()
    finally:
        conn.close()
    return out
