"""
Deployment models.

Represents a live (paper-trading) deployment of a strategy or portfolio.
Includes sleeves, trade alerts, and trade executions.

Maps directly to the deployments/sleeves/trade_alerts/trade_executions DB tables.
"""

from __future__ import annotations

from typing import Literal
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Deployment
# ---------------------------------------------------------------------------

class Deployment(BaseModel):
    """A live deployment record."""
    id: str
    type: Literal["strategy", "portfolio"] = Field(description="Display type. Internally everything is a portfolio.")
    name: str
    config_json: dict = Field(description="Frozen portfolio-format config at deploy time.")
    start_date: str
    initial_capital: float
    status: Literal["active", "paused", "stopped"] = "active"
    created_at: str
    updated_at: str

    # Latest evaluation metrics
    last_evaluated: str | None = None
    last_nav: float | None = None
    last_return_pct: float | None = None
    last_alpha_pct: float | None = None
    last_benchmark_return_pct: float | None = None
    last_sharpe_ratio: float | None = None
    last_max_drawdown_pct: float | None = None
    last_ann_volatility_pct: float | None = None
    rolling_vol_30d_pct: float | None = None

    total_trades: int = 0
    open_positions: int = 0
    current_utilization_pct: float | None = None
    peak_utilized_capital: float | None = None
    avg_utilized_capital: float | None = None
    utilization_pct: float | None = None
    return_on_utilized_capital_pct: float | None = None

    # Portfolio-specific
    num_sleeves: int = 1
    active_regimes: list[str] = Field(default_factory=list, description="Currently active regime names.")
    sleeve_summary: list[dict] = Field(default_factory=list, description="Per-sleeve metric snapshots.")

    alert_mode: bool = False
    error: str | None = None


# ---------------------------------------------------------------------------
# Deployment Sleeve
# ---------------------------------------------------------------------------

class DeploymentSleeve(BaseModel):
    """Per-sleeve state within a deployment."""
    sleeve_id: str
    portfolio_id: str | None = None
    deployment_id: str | None = None
    source_type: str
    source_id: str
    label: str
    strategy_id: str | None = None
    config_json: dict | None = None
    weight: float
    regime_gate: list[str] = Field(default_factory=list)
    allocated_capital: float | None = None
    is_active: bool = True

    # Metrics
    last_nav: float | None = None
    last_return_pct: float | None = None
    sharpe: float | None = None
    max_drawdown_pct: float | None = None
    profit_factor: float | None = None
    win_rate_pct: float | None = None

    total_trades: int = 0
    closed_trades: int = 0
    wins: int = 0
    losses: int = 0
    active_days: int = 0
    gated_off_days: int = 0

    created_at: str | None = None
    updated_at: str | None = None


# ---------------------------------------------------------------------------
# Trade Alert
# ---------------------------------------------------------------------------

class TradeAlert(BaseModel):
    """A pending trade signal generated by the deployment engine."""
    id: str
    deployment_id: str
    date: str
    action: str = Field(description="'BUY' or 'SELL'.")
    symbol: str
    shares: float
    target_price: float
    amount: float | None = None
    reason: str | None = None
    signal_detail: str | None = None
    entry_date: str | None = None
    entry_price: float | None = None
    pnl_pct: float | None = None
    pnl: float | None = None
    days_held: int | None = None
    sleeve_label: str | None = None
    created_at: str | None = None


# ---------------------------------------------------------------------------
# Trade Execution
# ---------------------------------------------------------------------------

class TradeExecution(BaseModel):
    """Record of a trade alert being executed (or skipped)."""
    id: str
    alert_id: str
    status: Literal["pending", "executed", "skipped"] = "pending"
    fill_price: float | None = None
    fill_time: str | None = None
    fill_shares: float | None = None
    broker: str = "manual"
    slippage_pct: float | None = None
    notes: str | None = None
    updated_at: str | None = None
